name: Stress testing on Godwoken testnet

on:
  push:
    branches:
    - "benchmark"
  workflow_dispatch:
    inputs:
      account_num:
        description: 'The number of accounts used for testing'
        required: false
        default: '50'

jobs:
  batch-deposits:
    runs-on: ubuntu-latest
    if: ${{ true }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Node Cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Generate the configs of testnet
      working-directory: tools
      run: yarn && yarn generate-testnet-configs && yarn build-all

    - name: Batch deposits from layer1 to layer2
      working-directory: tools/packages/tools
      env:
        ACCOUNT_NUM: 265
      run: |
        yarn ts-node src/benchmark/batch-deposits.ts $ACCOUNT_NUM

    - name: Setup tmate session for debugging if something failed
      if: ${{ failure() || cancelled() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 10

  
  batch-withdrawals:
    runs-on: ubuntu-latest
    if: ${{ true }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Node Cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Generate the configs of testnet
      working-directory: tools
      run: yarn && yarn generate-testnet-configs && yarn build-all

    - name: Batch withdraw-request from layer2 to layer1
      working-directory: tools/packages/tools
      env:
        ACCOUNT_NUM: 2
      run: |
        yarn ts-node src/benchmark/batch-withdrawals.ts $ACCOUNT_NUM
    
    - name: Setup tmate session for debugging if something failed
      if: ${{ failure() || cancelled() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 10
  
  batch-transactions:
    runs-on: ubuntu-latest
    if: ${{ true }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Node Cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Generate the configs of testnet
      working-directory: tools
      run: yarn && yarn generate-testnet-configs && yarn build-all

    # TODO: use scripts from @magicalne
    # - name: Testcase - Godwoken Polyjuice Compatibility Examples
    #   working-directory: testcases/godwoken-polyjuice-compatibility-examples
    #   run: |

    - name: Testcase - Pancakeswap
      working-directory: testcases/pancakeswap-contracts-godwoken
      run: |
        yarn && yarn compile

        PrivKeys=(
          '01e3b36f5876291a6ee7b573329b33706a67be0dabcb0d91387684770ff7bb44'
          'dd50cac37ec6dd12539a968c1a2cbedda75bd8724f7bcad486548eaabb87fc8b'
          '1390c30e5d5867ee7246619173b5922d3b04009cab9e9d91e14506231281a997'
          '2dc6374a2238e414e51874f514b0fa871f8ce0eb1e7ecaa0aed229312ffc91b0'
          '15f0805f5ebabda961cca1e97cdae03919b07d3eee4a9074c075ee2e80f2da9f'
          'a786cd647b24acbdc8ca46757dff3a930744179b6e20d9d8813c9430f954bd73'
          '21c3849c1d6d150f50806e773458df00c4501118e38f777b4110d50f38d91bfd'
          '1bd5d82ce33bfeb5824a919127f3f95c50314c1ca72c1fb7c370f3c79ecbe8e6'
          'acc5997a76ee194e4406b5e4e020efd6ca53dc3276c3d43753d55e936335c25d'
          'e2b0be6ffdba34a9d1e906f3a83ad24440ea22673b709306b1bc3b51030f79f3'
          '65d50620ad7f08ef4da10e9992062626daddc3b68907012ece845e9bbc8c14ff'
          'd1017ca5b9f0242818a33acd18911caadab84c8c92331eb2ecd2b44895e1d099'
          '991494a67bcfa4c30807f5a1426eaad2b79845672913c259da16926711328ae9'
          '7f52aecd6e71e2ca3c6dd4b2b82212767598006aee0718f140a8bd0647d2832c'
          '3826f69f59026faca8aa97f40cd512597b8801ebc40a88db19216d1742fdf4e7'
          '6edf8a51e2abb4543cacaa57aee366c95d25c8cffe4b41b0a7431d902c81080b'
          'dc181bbbc3d89ffad393e556949b56e2b44d2d4050d931262b559ef08e5eaf41'
          'b9a9aafa95299e1d149aca1f002e20a697846889c6540cd37a99193cdc3e742a'
          '2adc9f91e9686c0838c990e0ad9893ba32fdffa33341eb295cef3b1b0027d8c8'
          'f59c5e9cfe8ed57a4cda42046fa78fdb016002a651eae27bad65b4ade81dad51'
          '68777010f63b24b117f7bb28848b9c841d341b3f02b632ae2f6cdf59c6cd575e'
          'd5ffdf1c0c22c29ac05e7fd15113c47d23c59e671032a4a91f88e989c45aa9a5'
        )
        for i in "${PrivKeys[@]}"; do
          sed -i \
            -e "s|DEPLOYER_PRIVATE_KEY=.*|DEPLOYER_PRIVATE_KEY=${i}|g" \
            .env
          cat .env
          yarn ts-node ./scripts/deploy.ts &
        done
        sleep 360
      timeout-minutes: 6

    # - name: Testcase - LendingContracts
    #   working-directory: testcases/lending-contracts
    #   run: |
    #     yarn
    #     echo "The configs should have been updated:"
    #     cat config.json
    #     yarn deploy
    #   timeout-minutes: 12


  # TODO: Unlock the withdrawable funds to complete the withdrawal process